productpage:
  namespace: productpage-uat
  image: harbor.banjo.opsta.in.th/bootcamp/productpage
  tag: uat
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 9080
  healthCheckPath: "/health"

ingress:
  host: productpageuat.banjo.opsta.in.th
  path: "/?(.*)"
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: letsencrypt-prod

extraEnv:
  COMMIT_ID: CHANGME
  DETAILS_HOSTNAME: "https://detailsuat.banjo.opsta.in.th/details"
  RATINGS_HOSTNAME: "https://iloveyou.banjo.opsta.in.th/ratings"
  REVIEWS_HOSTNAME: "https://reviewsuat.banjo.opsta.in.th/reviews"