apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: bookinfo-dev
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: punthanat.u@opsta.co.th
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
          podTemplate:
            spec:
              nodeSelector:
                "kubernetes.io/os": linux