details:
  namespace: details-prd
  image: harbor.banjo.opsta.in.th/bootcamp/details
  tag: prd
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8080
  healthCheckPath: "/health"

ingress:
  host: detailsprd.banjo.opsta.in.th
  path: "/details(/|$)(.*)"
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: letsencrypt-prod

extraEnv:
  COMMIT_ID: CHANGME