ratings:
  namespace: bookinfo-prd
  image: harbor.banjo.opsta.in.th/bootcamp/ratings
  tag: prd
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8080
  healthCheckPath: "/health"
  mongodbPasswordExistingSecret: bookinfo-prd-ratings-mongodb-secret
ingress:
  host: iveryloveyou.banjo.opsta.in.th
  path: "/ratings(/|$)(.*)"
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: letsencrypt-prod
  
extraEnv:
  SERVICE_VERSION: v2
  MONGO_DB_URL: mongodb://bookinfo-prd-ratings-mongodb:27017/?authSource=ratings-prd
  MONGO_DB_NAME: ratings-prd
  MONGO_DB_USERNAME: ratings-prd
  COMMIT_ID: CHANGME