reviews:
  namespace: reviews-prd
  image: harbor.banjo.opsta.in.th/bootcamp/reviews
  tag: prd
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 9080
  healthCheckPath: "/health"

ingress:
  host: reviewsprd.banjo.opsta.in.th
  path: "/reviews(/|$)(.*)"
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: letsencrypt-prod

extraEnv:
  ENABLE_RATINGS: True
  RATINGS_SERVICE: https://iloveyou.banjo.opsta.in.th/ratings
  COMMIT_ID: CHANGME