apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: {{ .Values.jenkins.namespace }}
spec:
  type: {{ .Values.ingress.serviceType  }}
  ports:
  - port: {{ .Values.jenkins.port }}
  selector:
    app: jenkins-server