apiVersion: v1
description: Bookinfo Ratings Service Helm Chart
name: bookinfo-ratings
version: 1.0.0
appVersion: 1.0.0
home: https://details{dev,uat,prd}.banjo.opsta.in.th/details/details
maintainers:
  - name: Punthanat Ularnwiriyanont
    email: punthanat.u@opsta.co.th
sources:
  - https://gitlab.com/punthanat1/details
